---
- name: install | Defining Auto Update CLI Option
  set_fact:
    auto_update_cli_option: "{{ netdata_auto_updates['enabled']|ternary('--auto-update', '') }}"

- name: install | Cloning {{ netdata_git_repo }} to {{ netdata_source_dir }}
  git:
    repo: "{{ netdata_git_repo }}"
    dest: "{{ netdata_source_dir }}"
    depth: 1
    version: "{{ netdata_git_version_tag }}"
  become: true

- name: install | Installing Netdata ({{ netdata_installer }}) From {{ netdata_source_dir }}
  command: "{{ installer_cli|join(' ') }}"
  vars:
    installer_cli:
      - "{{ netdata_installer }}"
      - "{{ auto_update_cli_option }}"
      - "--dont-wait"
  args:
    chdir: "{{ netdata_source_dir }}"
    creates: /usr/sbin/netdata
  become: true
  notify: restart netdata
  when: netdata_install_method == "normal"


- name: install | Installing Netdata using kickstart From {{ netdata_source_dir }}
  command: "{{ installer_cli|join(' ') }}"
  vars:
    installer_cli:
      - "{{ netdata_kickstart_installer }}"
      - "--dont-wait"
  args:
    chdir: "{{ netdata_source_dir }}"
    creates: /usr/sbin/netdata
  become: true
  notify: restart netdata
  when: netdata_install_method == "kickstart"
