---
# tasks file for ansible-netdata

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: install.yml
  when: not netdata_uninstall

- include: config.yml
  when: 
    - netdata_config
    - not netdata_uninstall

- include: update.yml
  when: netdata_update or netdata_update_force

- include: auto_updates.yml
  when: netdata_auto_updates['enabled']

- include: uninstall.yml
  when: netdata_uninstall
  tags:
    - netdata_uninstall
