---
- stat:
    path: "{{ netdata_source_dir }}/packaging/installer/netdata-uninstaller.sh"
  register: uninstaller

- stat:
    path: "/etc/netdata/.environment"
  register: environment

- name: uninstall | Uninstalling Netdata # noqa 301
  command: "{{ netdata_uninstaller }} --yes"
  args:
    chdir: "{{ netdata_source_dir }}/packaging/installer/"
  become: true
  when: 
    - environment.stat.exists is defined
    - uninstaller.stat.exists is defined