---
- stat:
    path: "{{ netdata_source_dir }}/packaging/installer/netdata-uninstaller.sh"
  register: uninstaller

- stat:
    path: "/etc/netdata/.environment"
  register: environment_file

- name: uninstall | Uninstalling Netdata # noqa 301
  command: "{{ netdata_uninstaller }} --yes"
  args:
    chdir: "{{ netdata_source_dir }}/packaging/installer/"
  become: true
  when: 
    - environment_file.stat.exists
    - uninstaller.stat.exists

- name: Remove compiled executable
  file:
    path: /usr/sbin/netdata
    state: absent